apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: second-app-deployment
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: front
  template:
    metadata: 
      labels:
        app: second-app
        tier: front
    spec:
      containers:
          name: second-node
          image: amirad1/react:10
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: second-app
  namespace: frontend
spec:
  selector: 
    app: second-app
  ports:
  - port: 80
    NodePort: 3000
  type: NodePort
